# Generated by Django 4.1.2 on 2022-11-03 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=None)),
                ('name', models.TextField(max_length=128)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('address', models.TextField(max_length=128)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('description', models.TextField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_capacity', models.IntegerField()),
                ('available', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parkingplace_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zona de Parqueo',
                'verbose_name_plural': 'Zonas de Parqueo',
            },
        ),
    ]
