# Generated by Django 4.1.2 on 2022-11-03 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking_place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=None)),
                ('code', models.TextField(max_length=256)),
                ('name', models.TextField(max_length=128)),
                ('ip_cam', models.TextField(max_length=256)),
                ('ref_location', models.TextField(max_length=256)),
                ('note', models.TextField(blank=True, max_length=256)),
                ('pos_sup_x', models.IntegerField(null=True)),
                ('pos_sup_y', models.IntegerField(null=True)),
                ('pos_inf_x', models.IntegerField(null=True)),
                ('pos_inf_y', models.IntegerField(null=True)),
                ('places', models.IntegerField(default=1)),
                ('parking_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkingplace_camera', to='parking_place.parkingplace')),
            ],
            options={
                'verbose_name': 'Camara',
                'verbose_name_plural': 'Camaras',
            },
        ),
    ]
