# Generated by Django 4.1.2 on 2022-10-10 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='available_places',
            new_name='places',
        ),
    ]
