# Generated by Django 4.1.2 on 2022-11-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='active',
            field=models.IntegerField(default=1),
        ),
    ]
