# Generated by Django 4.1.2 on 2022-11-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_camera_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
